apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.fullname" . }}-migrations
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: "migrations"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
spec:
  activeDeadlineSeconds: {{ .Values.migrations.activeDeadlineSeconds }}
  template:
    metadata:
      {{- with .Values.migrations.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "migrations"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.migrations.podSecurityContext | nindent 8 }}
      containers:
        - name: migrations
          securityContext:
            {{- toYaml .Values.migrations.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            {{- with .Values.migrations.command }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
